# Generated by Django 3.1.2 on 2020-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clean_diet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Half', 'Half')], max_length=5)),
                ('coding', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Half', 'Half')], max_length=5)),
                ('reading', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Half', 'Half')], max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wakeup_early', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Half', 'Half')], max_length=5)),
            ],
        ),
    ]
